In [1]:
# set environment
import pandas as pd

In [2]:
PATH = "../00_data/raw/population.csv.gz"

# load the data
df = pd.read_csv(PATH)

# read the data
df

         YEAR   HHWT        CLUSTER  STATEFIP  PERNUM  CBPERNUM  PERWT   SLWT
0        2006  338.0  2006002062991         8       1         1  336.0  336.0
1        2006  338.0  2006002062991         8       2         2  208.0  208.0
2        2006  338.0  2006002062991         8       3         3  205.0  205.0
3        2006   83.0  2006002063001         8       1         1   82.0   82.0
4        2006   83.0  2006002063001         8       2         2   86.0   86.0
...       ...    ...            ...       ...     ...       ...    ...    ...
5918598  2015   72.0  2015013379091        53       2         2   61.0   61.0
5918599  2015   66.0  2015013379101        53       1         1   67.0   67.0
5918600  2015   66.0  2015013379101        53       2         2   60.0   60.0
5918601  2015  105.0  2015013379111        53       1         1  104.0  104.0
5918602  2015  105.0  2015013379111        53       2         2  110.0  110.0

[5918603 rows x 8 columns]

In [4]:
# choose the data we need to use
df = df[["YEAR", "STATEFIP", "PERWT"]]

# catgorize groups for future use
florida_group = [12]  # FL
florida_controls = [13, 45, 37]  # GA, SC, NC
washington_group = [53]  # WA
washington_controls = [41, 30, 8]  # OR, MT, CO

# select states
selected_fips = (
    florida_group + florida_controls + washington_group + washington_controls
)
df = df[df["STATEFIP"].isin(selected_fips)]

# check all data again
df

         YEAR  STATEFIP  PERWT
0        2006         8  336.0
1        2006         8  208.0
2        2006         8  205.0
3        2006         8   82.0
4        2006         8   86.0
...       ...       ...    ...
5918598  2015        53   61.0
5918599  2015        53   67.0
5918600  2015        53   60.0
5918601  2015        53  104.0
5918602  2015        53  110.0

[5918603 rows x 3 columns]

In [ ]:
# group the data to (state, year)
state_year = df.groupby(["STATEFIP", "YEAR"]).agg(POP=("PERWT", "sum")).reset_index()

# check the data
state_year

    STATEFIP  YEAR        POP
0          8  2006  4753377.0
1          8  2007  4861515.0
2          8  2008  4939456.0
3          8  2009  5024748.0
4          8  2010  5049071.0
..       ...   ...        ...
75        53  2011  6830038.0
76        53  2012  6897012.0
77        53  2013  6971406.0
78        53  2014  7061530.0
79        53  2015  7170351.0

[80 rows x 3 columns]

In [ ]:
OUTPUT_PATH = "../00_data/clean/state_population_clean.csv"

# output file for future use
state_year.to_csv(OUTPUT_PATH, index=False)
print(f"Cleaned data saved to: {OUTPUT_PATH}")

Cleaned data saved to: ../00_data/clean/state_population_clean.csv