In [1]:
import pandas as pd
import glob

# Where raw txt files were stored
RAW_PATH = "/Users/rosellazheng/Desktop/US_VitalStatistics/"
pattern = RAW_PATH + "Underlying Cause of Death, 20*.txt"

files = glob.glob(pattern)
print("Found files:", files)  # All are in there

# Combine all years
df = pd.concat((pd.read_csv(f, sep="\t") for f in files), ignore_index=True)

# Quick clean of column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# 3. Save into project repo so everyone else can load this CSV
OUTPUT = "/Users/rosellazheng/Desktop/idsproject/vital_stats_2003_2015.csv"
df.to_csv(OUTPUT, index=False)

print("Saved clean CSV to:", OUTPUT)

Found files: ['/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2009.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2008.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2003.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2014.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2015.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2005.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2011.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2010.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2004.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2012.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2006.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2007.txt', '/Users/rosellazheng/Desktop/US_VitalStatistics/Underlying Cause of Death, 2013.txt']
Saved clean CSV to: /Users/rosellazheng/Desktop/idsproject/vital_stats_2003_2015.csv

In [2]:
print("Total rows after concat:", len(df))  # 57436

Total rows after concat: 57436

In [3]:
# load the data
df = pd.read_csv(OUTPUT)

# basic info
print(f"Raw data shape: {df.shape}")

# quick look at the raw data
df

Raw data shape: (57436, 8)

,notes,county,county_code,year,year_code,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths
0,NaN,"Autauga County, AL",1001.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,NaN,"Baldwin County, AL",1003.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,NaN,"Baldwin County, AL",1003.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,NaN,"Barbour County, AL",1005.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,NaN,"Bibb County, AL",1007.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0
...,...,...,...,...,...,...,...,...
57431,Suggested Citation: Centers for Disease Contro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57432,"1999-2017 on CDC WONDER Online Database, relea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
57433,compiled from data provided by the 57 vital st...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57434,at http://wonder.cdc.gov/ucd-icd10.html on Oct...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57435,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns.unique()  # found all the column names

Index(['notes', 'county', 'county_code', 'year', 'year_code',
       'drug/alcohol_induced_cause', 'drug/alcohol_induced_cause_code',
       'deaths'],
      dtype='object')

In [ ]:
df_clean = df[
    df["notes"].isna()
]  # this is droping all the weird notes (correct to have NA)

In [7]:
print("Total rows after concat:", len(df_clean))  # 57241

Total rows after concat: 57241

In [8]:
df_clean = df_clean.drop(columns=["notes", "year_code"])

In [9]:
print(df_clean.columns)

Index(['county', 'county_code', 'year', 'drug/alcohol_induced_cause',
       'drug/alcohol_induced_cause_code', 'deaths'],
      dtype='object')

In [10]:
df_clean.head()

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths
0,"Autauga County, AL",1001.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,"Baldwin County, AL",1003.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,"Baldwin County, AL",1003.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,"Barbour County, AL",1005.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,"Bibb County, AL",1007.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0

In [11]:
# here we want to split the county column and make a new one just for state
df_clean[["county", "state"]] = df_clean["county"].str.split(", ", expand=True)

In [12]:
df_clean  # here we see its in the format we want

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
0,Autauga County,1001.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0,AL
1,Baldwin County,1003.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0,AL
2,Baldwin County,1003.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0,AL
3,Barbour County,1005.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0,AL
4,Bibb County,1007.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0,AL
...,...,...,...,...,...,...,...
57416,Sweetwater County,56037.0,2013.0,All other non-drug and non-alcohol causes,O9,238.0,WY
57417,Teton County,56039.0,2013.0,All other non-drug and non-alcohol causes,O9,83.0,WY
57418,Uinta County,56041.0,2013.0,All other non-drug and non-alcohol causes,O9,130.0,WY
57419,Washakie County,56043.0,2013.0,All other non-drug and non-alcohol causes,O9,72.0,WY
57420,Weston County,56045.0,2013.0,All other non-drug and non-alcohol causes,O9,66.0,WY

In [13]:
print("Total rows after concat:", len(df_clean))  # 57241

Total rows after concat: 57241

In [14]:
# here we can change both county_code and year into int
df_clean.dtypes

county                              object
county_code                        float64
year                               float64
drug/alcohol_induced_cause          object
drug/alcohol_induced_cause_code     object
deaths                              object
state                               object
dtype: object

In [15]:
# check for catorgories and make final dataset
df_clean["drug/alcohol_induced_cause"].unique()

array(['All other non-drug and non-alcohol causes',
       'Drug poisonings (overdose) Unintentional (X40-X44)',
       'Drug poisonings (overdose) Undetermined (Y10-Y14)',
       'Drug poisonings (overdose) Suicide (X60-X64)',
       'All other drug-induced causes',
       'All other alcohol-induced causes',
       'Alcohol poisonings (overdose) (X45, X65, Y15)',
       'Drug poisonings (overdose) Homicide (X85)'], dtype=object)

In [16]:
# keep only the unintentional
df_overdose = df_clean[
    df_clean["drug/alcohol_induced_cause"]
    == "Drug poisonings (overdose) Unintentional (X40-X44)"
]

In [17]:
df_overdose

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
1,Baldwin County,1003.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0,AL
8,Calhoun County,1015.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12.0,AL
30,Etowah County,1055.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,AL
38,Houston County,1069.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,AL
41,Jefferson County,1073.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,80.0,AL
...,...,...,...,...,...,...,...
57379,Washington County,55131.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,19.0,WI
57382,Waukesha County,55133.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,39.0,WI
57388,Winnebago County,55139.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WI
57403,Laramie County,56021.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,15.0,WY
57407,Natrona County,56025.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WY

In [18]:
df_overdose[
    "drug/alcohol_induced_cause_code"
].unique()  # check from code to see if only D1 left

array(['D1'], dtype=object)

In [19]:
print("Total rows after concat:", len(df_overdose))  # 7573

Total rows after concat: 7573

In [20]:
# keep every state except AK (alaska)
df_overdose = df_overdose[df_overdose["state"] != "AK"]

In [21]:
df_overdose

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
1,Baldwin County,1003.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0,AL
8,Calhoun County,1015.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12.0,AL
30,Etowah County,1055.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,AL
38,Houston County,1069.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,AL
41,Jefferson County,1073.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,80.0,AL
...,...,...,...,...,...,...,...
57379,Washington County,55131.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,19.0,WI
57382,Waukesha County,55133.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,39.0,WI
57388,Winnebago County,55139.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WI
57403,Laramie County,56021.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,15.0,WY
57407,Natrona County,56025.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WY

In [22]:
print("Total rows after concat:", len(df_overdose))  # 7538

Total rows after concat: 7538

In [ ]:
# change all the types to correct types
df_overdose["deaths"] = pd.to_numeric(df_overdose["deaths"], errors="coerce").astype(
    "Int64"
)
df_overdose["county"] = df_overdose["county"].astype("string")
df_overdose["county_code"] = df_overdose["county_code"].astype("Int64")
df_overdose["drug/alcohol_induced_cause"] = df_overdose[
    "drug/alcohol_induced_cause"
].astype("string")
df_overdose["drug/alcohol_induced_cause_code"] = df_overdose[
    "drug/alcohol_induced_cause_code"
].astype("string")
df_overdose["year"] = df_overdose["year"].astype(int)
df_overdose["county_code"] = df_overdose["county_code"].astype(int)
df_overdose["state"] = df_overdose["state"].astype("string")

/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["deaths"] = pd.to_numeric(df_overdose["deaths"], errors="coerce").astype(
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["county"] = df_overdose["county"].astype("string")
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["county_code"] = df_overdose["county_code"].astype("Int64")
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["drug/alcohol_induced_cause"] = df_overdose[
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["drug/alcohol_induced_cause_code"] = df_overdose[
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["year"] = df_overdose["year"].astype(int)
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["county_code"] = df_overdose["county_code"].astype(int)
/var/folders/vz/w47fmdn15gv7rywdldq7f0bw0000gn/T/ipykernel_70106/3363942364.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_overdose["state"] = df_overdose["state"].astype("string")

In [24]:
print("Total rows after concat:", len(df_overdose))  # should be same as before (7538)

Total rows after concat: 7538

In [25]:
df_overdose["drug/alcohol_induced_cause"].unique()

<StringArray>
['Drug poisonings (overdose) Unintentional (X40-X44)']
Length: 1, dtype: string

In [26]:
df_overdose

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
1,Baldwin County,1003,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,29,AL
8,Calhoun County,1015,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,12,AL
30,Etowah County,1055,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,14,AL
38,Houston County,1069,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,10,AL
41,Jefferson County,1073,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,80,AL
...,...,...,...,...,...,...,...
57379,Washington County,55131,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,19,WI
57382,Waukesha County,55133,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,39,WI
57388,Winnebago County,55139,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,14,WI
57403,Laramie County,56021,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,15,WY
57407,Natrona County,56025,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,14,WY

In [27]:
df_overdose.columns.unique

<bound method Index.unique of Index(['county', 'county_code', 'year', 'drug/alcohol_induced_cause',
       'drug/alcohol_induced_cause_code', 'deaths', 'state'],
      dtype='object')>

In [28]:
df_overdose.dtypes

county                             string[python]
county_code                                 int64
year                                        int64
drug/alcohol_induced_cause         string[python]
drug/alcohol_induced_cause_code    string[python]
deaths                                      Int64
state                              string[python]
dtype: object

In [30]:
# filter through the years that have overlapp between the datasets (with my groupmate)
# 2006 ~ 2015
df_overdose = df_overdose[(df_overdose["year"] >= 2006) & (df_overdose["year"] <= 2015)]

In [31]:
df_overdose

,county,county_code,year,drug/alcohol_induced_cause,drug/alcohol_induced_cause_code,deaths,state
1,Baldwin County,1003,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,29,AL
8,Calhoun County,1015,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,12,AL
30,Etowah County,1055,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,14,AL
38,Houston County,1069,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,10,AL
41,Jefferson County,1073,2009,Drug poisonings (overdose) Unintentional (X40-...,D1,80,AL
...,...,...,...,...,...,...,...
57379,Washington County,55131,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,19,WI
57382,Waukesha County,55133,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,39,WI
57388,Winnebago County,55139,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,14,WI
57403,Laramie County,56021,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,15,WY
57407,Natrona County,56025,2013,Drug poisonings (overdose) Unintentional (X40-...,D1,14,WY

In [32]:
print("Total rows after concat:", len(df_overdose))  # should be same as before (6300)

Total rows after concat: 6300

In [36]:
df_overdose["state"].value_counts()

state
CA    383
NC    354
TX    353
OH    353
FL    349
PA    345
GA    262
TN    230
NY    216
KY    211
IN    202
VA    179
MI    178
NJ    175
IL    173
WA    157
SC    149
AL    147
LA    144
WV    143
MO    136
OK    127
WI    117
MA    111
CO    105
NM     96
AZ     86
OR     82
CT     74
MN     65
AR     61
MS     53
UT     48
NH     48
ME     47
KS     46
MD     45
RI     32
IA     32
NV     31
ID     30
DE     28
NE     20
HI     19
MT     16
WY     15
VT     12
DC     10
SD      4
ND      1
Name: count, dtype: Int64

In [35]:
df_overdose["state"].value_counts().sum()  # check the amount of numbers for each state

np.int64(6300)

In [39]:
OUTPUT2 = "/Users/rosellazheng/Desktop/idsproject/df_overdose_cleaned.csv"
df_overdose.to_csv(OUTPUT2, index=False)